application: stip-blog
version: 2
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
